sudo: requied
services:
  - docker

before_install:
  - docker build -t dquez/rembr -f ./client/Dockerfile.dev ./client

script: 
  - docker run dquez/rembr npm test -- --coverage

after_success:
  - docker build -t dquez/rembr-client ./client
  - docker build -t dquez/rembr-nginx ./nginx
  - docker build -t dquez/rembr-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dquez/rembr-client
  - docker push dquez/rembr-nginx
  - docker push dquez/rembr-server